# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('body', models.TextField(verbose_name='具体内容')),
                ('body_html', models.TextField(verbose_name='渲染的html文本')),
                ('cover', models.CharField(max_length=100, verbose_name='文章的封面，可为空')),
                ('summary', models.TextField(help_text='可选项，若为空格则摘取正文前200个字符', max_length=200, verbose_name='简介')),
                ('post_date', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modify_date', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('visible', models.BooleanField(default=True, verbose_name='是否可见')),
                ('pwd', models.CharField(default='', max_length=10, verbose_name='是否设置密码')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('can_comment', models.BooleanField(default=True, verbose_name='是否可以评论')),
                ('top', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('catalog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Piper.Catalog', verbose_name='目录')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='标签')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, to='Piper.Tag', verbose_name='标签'),
        ),
    ]
